name: movie_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


 
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  equatable: ^2.0.5
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13




flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/avatar/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_native_splash:

  color: "#121312"
  image: assets/images/icon_splash.png
  branding: assets/images/branding_splash.png
  branding_bottom_padding: 24

  android_12:
    image: assets/images/icon_splash.png
    color: "#121312"
    branding: assets/images/branding_splash.png
